AZURE_OPENAI_KEY = "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"
AZURE_OPENAI_ENDPOINT = "https://aifa3shd001.openai.azure.com/"/"
AZURE_OPENAI_DEPLOYMENT = "o3-mini"
AZURE_OPENAI_API_VERSION = "5-03-01-preview"
SERPAPI_API_KEY = "7bbedd97dfdc157a7075185c1fd1fcd3cefe4603196bc49c810eb4e64a5ff3cd"
